# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/encryptGetPassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_getPasswordDialog(object):
    def setupUi(self, getPasswordDialog):
        getPasswordDialog.setObjectName("getPasswordDialog")
        getPasswordDialog.resize(395, 200)

        # --- Main label ---
        self.label = QtWidgets.QLabel(getPasswordDialog)
        self.label.setGeometry(QtCore.QRect(50, 10, 301, 41))
        self.label.setLineWidth(1)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        # --- Password field ---
        self.lineEdit = QtWidgets.QLineEdit(getPasswordDialog)
        self.lineEdit.setGeometry(QtCore.QRect(60, 60, 251, 31))
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setPlaceholderText("Enter password")
        self.lineEdit.setObjectName("lineEdit")

        # --- Confirm password field ---
        self.lineEdit_confirm = QtWidgets.QLineEdit(getPasswordDialog)
        self.lineEdit_confirm.setGeometry(QtCore.QRect(60, 100, 251, 31))
        self.lineEdit_confirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_confirm.setPlaceholderText("Confirm password")
        self.lineEdit_confirm.setObjectName("lineEdit_confirm")

        # --- Encrypt button ---
        self.pushButton = QtWidgets.QPushButton(getPasswordDialog)
        self.pushButton.setGeometry(QtCore.QRect(140, 150, 100, 32))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(getPasswordDialog)
        QtCore.QMetaObject.connectSlotsByName(getPasswordDialog)

    def retranslateUi(self, getPasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        getPasswordDialog.setWindowTitle(_translate("getPasswordDialog", "Enter Password"))
        self.label.setText(_translate("getPasswordDialog", "Please input and confirm your password to generate the encryption key"))
        self.pushButton.setText(_translate("getPasswordDialog", "Encrypt"))
