# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(393, 199)
        self.label = QtWidgets.QLabel(main)
        self.label.setGeometry(QtCore.QRect(0, 40, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(main)
        self.label_2.setGeometry(QtCore.QRect(0, 90, 111, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(main)
        self.pushButton.setGeometry(QtCore.QRect(50, 150, 80, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(main)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 40, 80, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(main)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 90, 80, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(main)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 150, 80, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(main)
        self.textEdit.setGeometry(QtCore.QRect(100, 40, 201, 21))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(main)
        self.textEdit_2.setGeometry(QtCore.QRect(100, 90, 201, 21))
        self.textEdit_2.setObjectName("textEdit_2")

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Dialog"))
        self.label.setText(_translate("main", "File to Encrypt"))
        self.label_2.setText(_translate("main", "Salt (to decrypt)"))
        self.pushButton.setText(_translate("main", "Encrypt"))
        self.pushButton_3.setText(_translate("main", "Browse"))
        self.pushButton_4.setText(_translate("main", "Browse"))
        self.pushButton_2.setText(_translate("main", "Decrypt"))
